import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { unlink, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";

import { councilCommand } from "./commands/council";
import { dashboardCommand } from "./commands/dashboard";
import { dispatchCommand } from "./commands/dispatch";
import { doctorCommand } from "./commands/doctor";
import { heartbeatCommand } from "./commands/heartbeat";
import { inboxCommand } from "./commands/inbox";
import { initCommand } from "./commands/init";
import { killCommand } from "./commands/kill";
import { memoryCommand } from "./commands/memory";
import { projectCommand } from "./commands/project";
import { psCommand } from "./commands/ps";
import { stackCommand } from "./commands/stack";
import { ticketCommand } from "./commands/ticket";
import { UsageError } from "./lib/errors";
import { extractHarnessFlag, resolveHarness } from "./lib/harness";
import { assembleIdentity, writeIdentityTempFile, cleanupIdentityTempFile, getIdentityName } from "./lib/identity";

const hiveCommands: Record<string, (args: string[]) => Promise<void>> = {
  init: initCommand,
  doctor: doctorCommand,
  project: projectCommand,
  stack: stackCommand,
  council: councilCommand,
  memory: memoryCommand,
  ticket: ticketCommand,
  dispatch: dispatchCommand,
  heartbeat: heartbeatCommand,
  inbox: inboxCommand,
  kill: killCommand,
  ps: psCommand,
  dashboard: dashboardCommand,
};

function getUsage(): string {
  const name = getIdentityName();
  return `Usage: hive [command] [args]

When called with a HIVE command, runs that command directly.
When called with anything else (or no args), launches Claude as ${name}.

HIVE Commands:
  init                       Set up ~/.hive and register MCP server
  doctor                     Validate installation health
  project add <name> <path>  Register a project
  stack list|install|sync    Manage language/framework skill stacks
  council "<question>"       Multi-model council deliberation
  memory [view|fact|...]     View or add project memory
  ticket [create|list|...]   Project ticket tracker
  dispatch "<goal>" [opts]   Dispatch autonomous goal execution
  heartbeat start|stop|...   Periodic project awareness
  inbox                      Show project inbox (clear with: inbox clear)
  kill <run-id>              Kill a running dispatch
  ps                         Show active and recent dispatch runs
  dashboard [build|open]     Build or open the Morning Edition dashboard

${name} (Claude with identity):
  hive                       Interactive ${name} session
  hive "fix the auth bug"    ${name} with a prompt
  hive --agent maya-coder    ${name} with a specific agent
  hive [any claude flags]    Passed through to claude with identity

Harness selection (hive-on-pi migration):
  (default)                  Pi with identity, MCP adapter, subscription OAuth
  -c, --claude-code          Route this invocation through Claude Code
  HIVE_HARNESS=claude-code   Env-var equivalent (applies to full session)`;
}

function findClaude(): string {
  try {
    return execSync("which claude", { encoding: "utf-8" }).trim();
  } catch {
    const fallback = join(process.env.HOME || "", ".local", "bin", "claude");
    if (existsSync(fallback)) return fallback;
    throw new Error("Could not find claude CLI. Is it installed?");
  }
}

function findPi(): string {
  try {
    return execSync("which pi", { encoding: "utf-8" }).trim();
  } catch {
    throw new Error(
      "Could not find pi CLI. Install: npm install -g @mariozechner/pi-coding-agent",
    );
  }
}

function piExtensionTempPath(): string {
  return join(tmpdir(), `hive-pi-ext-${process.pid}.ts`);
}

async function writePiExtensionTempFile(): Promise<string> {
  const identity = await assembleIdentity();
  const b64 = Buffer.from(identity, "utf-8").toString("base64");
  const hiveDir = process.env.HIVE_DIR || join(homedir(), ".hive");
  // Identity + observability, embedded. Canonical source lives in
  // packages/hive-pi/extensions/{identity,observability}.ts — keep in sync.
  const extSource = [
    "// Generated by hive launcher. Do not edit — regenerated each invocation.",
    "import { mkdir, symlink, writeFile } from \"node:fs/promises\";",
    "import { join } from \"node:path\";",
    "",
    `const IDENTITY_B64 = "${b64}";`,
    `const HIVE_DIR = ${JSON.stringify(hiveDir)};`,
    "const identityText = Buffer.from(IDENTITY_B64, \"base64\").toString(\"utf-8\");",
    "",
    "const compactTs = () => new Date().toISOString().replace(/[-:]/g, \"\").replace(/\\.\\d+Z$/, \"Z\");",
    "const makeRunId = (sid) => `PI-${compactTs()}-${sid.slice(0, 8)}`;",
    "",
    "export default function hiveRuntime(pi) {",
    "  // --- Identity: inject HIVE soul stack ahead of Pi's base system prompt.",
    "  pi.on(\"before_agent_start\", async (event) => ({",
    "    systemPrompt: identityText + \"\\n\\n---\\n\\n\" + event.systemPrompt,",
    "  }));",
    "",
    "  // --- Observability: mirror Pi session into ~/.hive/runs/<runId>/",
    "  let runDir, meta, symlinkDone = false;",
    "",
    "  const writeMeta = async () => {",
    "    if (!runDir || !meta) return;",
    "    await writeFile(join(runDir, \"meta.json\"), JSON.stringify(meta, null, 2) + \"\\n\", \"utf-8\");",
    "  };",
    "",
    "  const ensureRunDir = async (sessionId, cwd) => {",
    "    if (runDir) return;",
    "    const runId = makeRunId(sessionId);",
    "    runDir = join(HIVE_DIR, \"runs\", runId);",
    "    await mkdir(runDir, { recursive: true });",
    "    meta = { runId, sessionId, cwd, startedAt: new Date().toISOString() };",
    "    await writeMeta();",
    "  };",
    "",
    "  const ensureSymlink = async (sessionFile) => {",
    "    if (symlinkDone || !runDir) return;",
    "    try {",
    "      await symlink(sessionFile, join(runDir, \"session.jsonl\"));",
    "      symlinkDone = true;",
    "    } catch (err) {",
    "      if (err && err.code === \"EEXIST\") { symlinkDone = true; return; }",
    "      throw err;",
    "    }",
    "  };",
    "",
    "  pi.on(\"session_start\", async (_event, ctx) => {",
    "    try {",
    "      const sid = ctx.sessionManager.getSessionId();",
    "      const cwd = ctx.sessionManager.getCwd();",
    "      await ensureRunDir(sid, cwd);",
    "      const sf = ctx.sessionManager.getSessionFile();",
    "      if (sf) await ensureSymlink(sf);",
    "    } catch (err) {",
    "      try { ctx.ui.notify(`HIVE observability: ${err?.message || err}`, \"error\"); } catch {}",
    "    }",
    "  });",
    "",
    "  pi.on(\"message_end\", async (_event, ctx) => {",
    "    if (symlinkDone) return;",
    "    try {",
    "      const sf = ctx.sessionManager.getSessionFile();",
    "      if (sf) await ensureSymlink(sf);",
    "    } catch { /* retry next message */ }",
    "  });",
    "",
    "  pi.on(\"session_shutdown\", async () => {",
    "    try {",
    "      if (meta) { meta.endedAt = new Date().toISOString(); await writeMeta(); }",
    "    } catch { /* best-effort */ }",
    "  });",
    "}",
    "",
  ].join("\n");
  const tempPath = piExtensionTempPath();
  await writeFile(tempPath, extSource, "utf-8");
  return tempPath;
}

async function cleanupPiExtensionTempFile(): Promise<void> {
  if (process.env.HIVE_DEBUG_KEEP_EXT) return;
  try {
    await unlink(piExtensionTempPath());
  } catch {
    /* already gone */
  }
}

async function launchPi(args: string[]): Promise<void> {
  const extensionFile = await writePiExtensionTempFile();

  const cleanup = () => {
    void cleanupPiExtensionTempFile();
  };
  process.on("exit", cleanup);
  process.on("SIGINT", () => {
    cleanup();
    process.exit(130);
  });
  process.on("SIGTERM", () => {
    cleanup();
    process.exit(143);
  });

  const pi = findPi();

  const piArgs = ["-e", extensionFile, ...args];

  const result = Bun.spawnSync([pi, ...piArgs], {
    stdin: "inherit",
    stdout: "inherit",
    stderr: "inherit",
    env: {
      ...process.env,
      ANTHROPIC_API_KEY: undefined, // force subscription via auth.json
    },
  });

  cleanup();
  process.exit(result.exitCode ?? 0);
}

async function launchAgent(args: string[]): Promise<void> {
  const harness = resolveHarness();
  if (harness === "pi") return launchPi(args);
  return launchClaude(args);
}

async function launchClaude(args: string[]): Promise<void> {
  const identityFile = await writeIdentityTempFile();

  // Clean up on exit
  process.on("exit", cleanupIdentityTempFile);
  process.on("SIGINT", () => { cleanupIdentityTempFile(); process.exit(130); });
  process.on("SIGTERM", () => { cleanupIdentityTempFile(); process.exit(143); });

  const claude = findClaude();

  // Build claude args: identity injection + user args
  const claudeArgs = [
    "--append-system-prompt-file", identityFile,
    "--add-dir", join(process.env.HOME || "", ".hive"),
    ...args,
  ];

  // Replace this process with claude
  const result = Bun.spawnSync([claude, ...claudeArgs], {
    stdin: "inherit",
    stdout: "inherit",
    stderr: "inherit",
    env: {
      ...process.env,
      ANTHROPIC_API_KEY: undefined, // force subscription
    },
  });

  cleanupIdentityTempFile();
  process.exit(result.exitCode ?? 0);
}

async function main(): Promise<void> {
  const { forceClaudeCode, remaining: args } = extractHarnessFlag(process.argv.slice(2));
  if (forceClaudeCode) {
    process.env.HIVE_HARNESS = "claude-code";
  }
  const command = args[0];

  // No args → interactive session
  if (!command) {
    await launchAgent([]);
    return;
  }

  // Help
  if (command === "help" || command === "--help" || command === "-h") {
    console.log(getUsage());
    return;
  }

  // Known HIVE command → handle directly
  const handler = hiveCommands[command];
  if (handler) {
    try {
      await handler(args.slice(1));
    } catch (error) {
      if (error instanceof UsageError) {
        console.error(error.message);
        process.exit(1);
      }
      throw error;
    }
    return;
  }

  // Everything else → pass through to the active harness with identity
  await launchAgent(args);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
