import { execSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, rm, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";

// Canonical extension sources — embedded into the compiled hive binary at
// bundle time, written to temp files at launch, passed to pi via -e. Keeps
// packages/hive-pi/extensions/ as single source of truth.
import observabilitySource from "../packages/hive-pi/extensions/observability.ts" with { type: "text" };
import trustSource from "../packages/hive-pi/extensions/trust.ts" with { type: "text" };

import { councilCommand } from "./commands/council";
import { dashboardCommand } from "./commands/dashboard";
import { dispatchCommand } from "./commands/dispatch";
import { doctorCommand } from "./commands/doctor";
import { heartbeatCommand } from "./commands/heartbeat";
import { inboxCommand } from "./commands/inbox";
import { initCommand } from "./commands/init";
import { killCommand } from "./commands/kill";
import { memoryCommand } from "./commands/memory";
import { projectCommand } from "./commands/project";
import { psCommand } from "./commands/ps";
import { stackCommand } from "./commands/stack";
import { ticketCommand } from "./commands/ticket";
import { UsageError } from "./lib/errors";
import { extractHarnessFlag, resolveHarness } from "./lib/harness";
import { assembleIdentity, writeIdentityTempFile, cleanupIdentityTempFile, getIdentityName } from "./lib/identity";

const hiveCommands: Record<string, (args: string[]) => Promise<void>> = {
  init: initCommand,
  doctor: doctorCommand,
  project: projectCommand,
  stack: stackCommand,
  council: councilCommand,
  memory: memoryCommand,
  ticket: ticketCommand,
  dispatch: dispatchCommand,
  heartbeat: heartbeatCommand,
  inbox: inboxCommand,
  kill: killCommand,
  ps: psCommand,
  dashboard: dashboardCommand,
};

function getUsage(): string {
  const name = getIdentityName();
  return `Usage: hive [command] [args]

When called with a HIVE command, runs that command directly.
When called with anything else (or no args), launches Claude as ${name}.

HIVE Commands:
  init                       Set up ~/.hive and register MCP server
  doctor                     Validate installation health
  project add <name> <path>  Register a project
  stack list|install|sync    Manage language/framework skill stacks
  council "<question>"       Multi-model council deliberation
  memory [view|fact|...]     View or add project memory
  ticket [create|list|...]   Project ticket tracker
  dispatch "<goal>" [opts]   Dispatch autonomous goal execution
  heartbeat start|stop|...   Periodic project awareness
  inbox                      Show project inbox (clear with: inbox clear)
  kill <run-id>              Kill a running dispatch
  ps                         Show active and recent dispatch runs
  dashboard [build|open]     Build or open the Morning Edition dashboard

${name} (Claude with identity):
  hive                       Interactive ${name} session
  hive "fix the auth bug"    ${name} with a prompt
  hive --agent maya-coder    ${name} with a specific agent
  hive [any claude flags]    Passed through to claude with identity

Harness selection:
  (default)                  Claude Code with identity
  -3, --pi                   Route this invocation through Pi (subscription OAuth, MCP adapter)
  HIVE_HARNESS=pi            Env-var equivalent (applies to full session)`;
}

function findClaude(): string {
  try {
    return execSync("which claude", { encoding: "utf-8" }).trim();
  } catch {
    const fallback = join(process.env.HOME || "", ".local", "bin", "claude");
    if (existsSync(fallback)) return fallback;
    throw new Error("Could not find claude CLI. Is it installed?");
  }
}

function findPi(): string {
  try {
    return execSync("which pi", { encoding: "utf-8" }).trim();
  } catch {
    throw new Error(
      "Could not find pi CLI. Install: npm install -g @mariozechner/pi-coding-agent",
    );
  }
}

function piExtensionTempDir(): string {
  return join(tmpdir(), `hive-pi-ext-${process.pid}`);
}

/**
 * Writes the per-invocation extension bundle to a temp dir and returns
 * absolute paths for pi's -e flag. One file per extension:
 *   - identity.ts: runtime-generated, embeds the live HIVE identity stack
 *                  assembled from ~/.hive/
 *   - observability.ts, trust.ts: canonical sources from
 *                  packages/hive-pi/extensions/, embedded into the hive
 *                  binary at bundle time as text imports
 */
async function writePiExtensionTempFiles(): Promise<string[]> {
  const dir = piExtensionTempDir();
  await mkdir(dir, { recursive: true });

  const identity = await assembleIdentity();
  const b64 = Buffer.from(identity, "utf-8").toString("base64");
  const identitySource = [
    "// Generated by hive launcher — identity injection only.",
    `const IDENTITY_B64 = "${b64}";`,
    'const identityText = Buffer.from(IDENTITY_B64, "base64").toString("utf-8");',
    "export default function hiveIdentityRuntime(pi) {",
    '  pi.on("before_agent_start", async (event) => ({',
    '    systemPrompt: identityText + "\\n\\n---\\n\\n" + event.systemPrompt,',
    "  }));",
    "}",
    "",
  ].join("\n");

  const files: [name: string, source: string][] = [
    ["identity.ts", identitySource],
    ["observability.ts", observabilitySource],
    ["trust.ts", trustSource],
  ];

  const paths: string[] = [];
  for (const [name, source] of files) {
    const path = join(dir, name);
    await writeFile(path, source, "utf-8");
    paths.push(path);
  }
  return paths;
}

async function cleanupPiExtensionTempFiles(): Promise<void> {
  if (process.env.HIVE_DEBUG_KEEP_EXT) return;
  try {
    await rm(piExtensionTempDir(), { recursive: true, force: true });
  } catch {
    /* already gone */
  }
}

async function launchPi(args: string[]): Promise<void> {
  const extensionFiles = await writePiExtensionTempFiles();

  const cleanup = () => {
    void cleanupPiExtensionTempFiles();
  };
  process.on("exit", cleanup);
  process.on("SIGINT", () => {
    cleanup();
    process.exit(130);
  });
  process.on("SIGTERM", () => {
    cleanup();
    process.exit(143);
  });

  const pi = findPi();

  const piArgs = [...extensionFiles.flatMap((f) => ["-e", f]), ...args];

  const result = Bun.spawnSync([pi, ...piArgs], {
    stdin: "inherit",
    stdout: "inherit",
    stderr: "inherit",
    env: {
      ...process.env,
      ANTHROPIC_API_KEY: undefined, // force subscription via auth.json
    },
  });

  cleanup();
  process.exit(result.exitCode ?? 0);
}

async function launchAgent(args: string[]): Promise<void> {
  const harness = resolveHarness();
  if (harness === "pi") return launchPi(args);
  return launchClaude(args);
}

async function launchClaude(args: string[]): Promise<void> {
  const identityFile = await writeIdentityTempFile();

  // Clean up on exit
  process.on("exit", cleanupIdentityTempFile);
  process.on("SIGINT", () => { cleanupIdentityTempFile(); process.exit(130); });
  process.on("SIGTERM", () => { cleanupIdentityTempFile(); process.exit(143); });

  const claude = findClaude();

  // Build claude args: identity injection + user args
  const claudeArgs = [
    "--append-system-prompt-file", identityFile,
    "--add-dir", join(process.env.HOME || "", ".hive"),
    ...args,
  ];

  // Replace this process with claude
  const result = Bun.spawnSync([claude, ...claudeArgs], {
    stdin: "inherit",
    stdout: "inherit",
    stderr: "inherit",
    env: {
      ...process.env,
      ANTHROPIC_API_KEY: undefined, // force subscription
    },
  });

  cleanupIdentityTempFile();
  process.exit(result.exitCode ?? 0);
}

async function main(): Promise<void> {
  const { forcePi, remaining: args } = extractHarnessFlag(process.argv.slice(2));
  if (forcePi) {
    process.env.HIVE_HARNESS = "pi";
  }
  const command = args[0];

  // No args → interactive session
  if (!command) {
    await launchAgent([]);
    return;
  }

  // Help
  if (command === "help" || command === "--help" || command === "-h") {
    console.log(getUsage());
    return;
  }

  // Known HIVE command → handle directly
  const handler = hiveCommands[command];
  if (handler) {
    try {
      await handler(args.slice(1));
    } catch (error) {
      if (error instanceof UsageError) {
        console.error(error.message);
        process.exit(1);
      }
      throw error;
    }
    return;
  }

  // Everything else → pass through to the active harness with identity
  await launchAgent(args);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
